name: netify_monorepo
repository: https://github.com/ricoerlan/netify

packages:
  - packages/**

command:
  bootstrap:
    runPubGetInParallel: false

  version:
    branch: main
    message: "chore(release): publish packages"

scripts:
  analyze:
    run: flutter analyze
    description: Run static analysis on all packages

  format:
    run: dart format .
    description: Format all Dart files

  test:
    run: flutter test
    description: Run tests for all packages

  clean:
    run: flutter clean
    description: Clean all packages
